/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppMatrixRouteImport } from './routes/_app.matrix'
import { Route as AppDprRouteImport } from './routes/_app.dpr'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppTasksIndexRouteImport } from './routes/_app.tasks.index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppMaterialsIndexRouteImport } from './routes/_app.materials.index'
import { Route as AppLabourIndexRouteImport } from './routes/_app.labour.index'
import { Route as AppHrIndexRouteImport } from './routes/_app.hr.index'
import { Route as AppTasksIdRouteImport } from './routes/_app.tasks.$id'
import { Route as AppProjectsIdRouteImport } from './routes/_app.projects.$id'
import { Route as AppMaterialsRequestsRouteImport } from './routes/_app.materials.requests'
import { Route as AppMaterialsPurchaseOrdersRouteImport } from './routes/_app.materials.purchase-orders'
import { Route as AppMaterialsInventoryRouteImport } from './routes/_app.materials.inventory'
import { Route as AppMaterialsGrnRouteImport } from './routes/_app.materials.grn'
import { Route as AppLabourProductivityRouteImport } from './routes/_app.labour.productivity'
import { Route as AppLabourContractorsRouteImport } from './routes/_app.labour.contractors'
import { Route as AppLabourAttendanceRouteImport } from './routes/_app.labour.attendance'
import { Route as AppHrTrackingRouteImport } from './routes/_app.hr.tracking'
import { Route as AppHrSettingsRouteImport } from './routes/_app.hr.settings'
import { Route as AppHrReportsRouteImport } from './routes/_app.hr.reports'
import { Route as AppHrPayrollRouteImport } from './routes/_app.hr.payroll'
import { Route as AppHrLeaveRouteImport } from './routes/_app.hr.leave'
import { Route as AppHrAttendanceRouteImport } from './routes/_app.hr.attendance'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppMatrixRoute = AppMatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => AppRoute,
} as any)
const AppDprRoute = AppDprRouteImport.update({
  id: '/dpr',
  path: '/dpr',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsIndexRoute = AppMaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => AppRoute,
} as any)
const AppLabourIndexRoute = AppLabourIndexRouteImport.update({
  id: '/labour/',
  path: '/labour/',
  getParentRoute: () => AppRoute,
} as any)
const AppHrIndexRoute = AppHrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIdRoute = AppTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsRequestsRoute = AppMaterialsRequestsRouteImport.update({
  id: '/materials/requests',
  path: '/materials/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsPurchaseOrdersRoute =
  AppMaterialsPurchaseOrdersRouteImport.update({
    id: '/materials/purchase-orders',
    path: '/materials/purchase-orders',
    getParentRoute: () => AppRoute,
  } as any)
const AppMaterialsInventoryRoute = AppMaterialsInventoryRouteImport.update({
  id: '/materials/inventory',
  path: '/materials/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsGrnRoute = AppMaterialsGrnRouteImport.update({
  id: '/materials/grn',
  path: '/materials/grn',
  getParentRoute: () => AppRoute,
} as any)
const AppLabourProductivityRoute = AppLabourProductivityRouteImport.update({
  id: '/labour/productivity',
  path: '/labour/productivity',
  getParentRoute: () => AppRoute,
} as any)
const AppLabourContractorsRoute = AppLabourContractorsRouteImport.update({
  id: '/labour/contractors',
  path: '/labour/contractors',
  getParentRoute: () => AppRoute,
} as any)
const AppLabourAttendanceRoute = AppLabourAttendanceRouteImport.update({
  id: '/labour/attendance',
  path: '/labour/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppHrTrackingRoute = AppHrTrackingRouteImport.update({
  id: '/hr/tracking',
  path: '/hr/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppHrSettingsRoute = AppHrSettingsRouteImport.update({
  id: '/hr/settings',
  path: '/hr/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppHrReportsRoute = AppHrReportsRouteImport.update({
  id: '/hr/reports',
  path: '/hr/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppHrPayrollRoute = AppHrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppHrLeaveRoute = AppHrLeaveRouteImport.update({
  id: '/hr/leave',
  path: '/hr/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppHrAttendanceRoute = AppHrAttendanceRouteImport.update({
  id: '/hr/attendance',
  path: '/hr/attendance',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/approvals': typeof AppApprovalsRoute
  '/dashboard': typeof AppDashboardRoute
  '/dpr': typeof AppDprRoute
  '/matrix': typeof AppMatrixRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/hr/attendance': typeof AppHrAttendanceRoute
  '/hr/leave': typeof AppHrLeaveRoute
  '/hr/payroll': typeof AppHrPayrollRoute
  '/hr/reports': typeof AppHrReportsRoute
  '/hr/settings': typeof AppHrSettingsRoute
  '/hr/tracking': typeof AppHrTrackingRoute
  '/labour/attendance': typeof AppLabourAttendanceRoute
  '/labour/contractors': typeof AppLabourContractorsRoute
  '/labour/productivity': typeof AppLabourProductivityRoute
  '/materials/grn': typeof AppMaterialsGrnRoute
  '/materials/inventory': typeof AppMaterialsInventoryRoute
  '/materials/purchase-orders': typeof AppMaterialsPurchaseOrdersRoute
  '/materials/requests': typeof AppMaterialsRequestsRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/tasks/$id': typeof AppTasksIdRoute
  '/hr/': typeof AppHrIndexRoute
  '/labour/': typeof AppLabourIndexRoute
  '/materials/': typeof AppMaterialsIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/approvals': typeof AppApprovalsRoute
  '/dashboard': typeof AppDashboardRoute
  '/dpr': typeof AppDprRoute
  '/matrix': typeof AppMatrixRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/hr/attendance': typeof AppHrAttendanceRoute
  '/hr/leave': typeof AppHrLeaveRoute
  '/hr/payroll': typeof AppHrPayrollRoute
  '/hr/reports': typeof AppHrReportsRoute
  '/hr/settings': typeof AppHrSettingsRoute
  '/hr/tracking': typeof AppHrTrackingRoute
  '/labour/attendance': typeof AppLabourAttendanceRoute
  '/labour/contractors': typeof AppLabourContractorsRoute
  '/labour/productivity': typeof AppLabourProductivityRoute
  '/materials/grn': typeof AppMaterialsGrnRoute
  '/materials/inventory': typeof AppMaterialsInventoryRoute
  '/materials/purchase-orders': typeof AppMaterialsPurchaseOrdersRoute
  '/materials/requests': typeof AppMaterialsRequestsRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/tasks/$id': typeof AppTasksIdRoute
  '/hr': typeof AppHrIndexRoute
  '/labour': typeof AppLabourIndexRoute
  '/materials': typeof AppMaterialsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dpr': typeof AppDprRoute
  '/_app/matrix': typeof AppMatrixRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/hr/attendance': typeof AppHrAttendanceRoute
  '/_app/hr/leave': typeof AppHrLeaveRoute
  '/_app/hr/payroll': typeof AppHrPayrollRoute
  '/_app/hr/reports': typeof AppHrReportsRoute
  '/_app/hr/settings': typeof AppHrSettingsRoute
  '/_app/hr/tracking': typeof AppHrTrackingRoute
  '/_app/labour/attendance': typeof AppLabourAttendanceRoute
  '/_app/labour/contractors': typeof AppLabourContractorsRoute
  '/_app/labour/productivity': typeof AppLabourProductivityRoute
  '/_app/materials/grn': typeof AppMaterialsGrnRoute
  '/_app/materials/inventory': typeof AppMaterialsInventoryRoute
  '/_app/materials/purchase-orders': typeof AppMaterialsPurchaseOrdersRoute
  '/_app/materials/requests': typeof AppMaterialsRequestsRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/tasks/$id': typeof AppTasksIdRoute
  '/_app/hr/': typeof AppHrIndexRoute
  '/_app/labour/': typeof AppLabourIndexRoute
  '/_app/materials/': typeof AppMaterialsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/approvals'
    | '/dashboard'
    | '/dpr'
    | '/matrix'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/users'
    | '/hr/attendance'
    | '/hr/leave'
    | '/hr/payroll'
    | '/hr/reports'
    | '/hr/settings'
    | '/hr/tracking'
    | '/labour/attendance'
    | '/labour/contractors'
    | '/labour/productivity'
    | '/materials/grn'
    | '/materials/inventory'
    | '/materials/purchase-orders'
    | '/materials/requests'
    | '/projects/$id'
    | '/tasks/$id'
    | '/hr/'
    | '/labour/'
    | '/materials/'
    | '/projects/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/approvals'
    | '/dashboard'
    | '/dpr'
    | '/matrix'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/users'
    | '/hr/attendance'
    | '/hr/leave'
    | '/hr/payroll'
    | '/hr/reports'
    | '/hr/settings'
    | '/hr/tracking'
    | '/labour/attendance'
    | '/labour/contractors'
    | '/labour/productivity'
    | '/materials/grn'
    | '/materials/inventory'
    | '/materials/purchase-orders'
    | '/materials/requests'
    | '/projects/$id'
    | '/tasks/$id'
    | '/hr'
    | '/labour'
    | '/materials'
    | '/projects'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/sitemap.xml'
    | '/_app/approvals'
    | '/_app/dashboard'
    | '/_app/dpr'
    | '/_app/matrix'
    | '/_app/reports'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/users'
    | '/_app/hr/attendance'
    | '/_app/hr/leave'
    | '/_app/hr/payroll'
    | '/_app/hr/reports'
    | '/_app/hr/settings'
    | '/_app/hr/tracking'
    | '/_app/labour/attendance'
    | '/_app/labour/contractors'
    | '/_app/labour/productivity'
    | '/_app/materials/grn'
    | '/_app/materials/inventory'
    | '/_app/materials/purchase-orders'
    | '/_app/materials/requests'
    | '/_app/projects/$id'
    | '/_app/tasks/$id'
    | '/_app/hr/'
    | '/_app/labour/'
    | '/_app/materials/'
    | '/_app/projects/'
    | '/_app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matrix': {
      id: '/_app/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof AppMatrixRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dpr': {
      id: '/_app/dpr'
      path: '/dpr'
      fullPath: '/dpr'
      preLoaderRoute: typeof AppDprRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materials/': {
      id: '/_app/materials/'
      path: '/materials'
      fullPath: '/materials/'
      preLoaderRoute: typeof AppMaterialsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labour/': {
      id: '/_app/labour/'
      path: '/labour'
      fullPath: '/labour/'
      preLoaderRoute: typeof AppLabourIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/': {
      id: '/_app/hr/'
      path: '/hr'
      fullPath: '/hr/'
      preLoaderRoute: typeof AppHrIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$id': {
      id: '/_app/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AppTasksIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materials/requests': {
      id: '/_app/materials/requests'
      path: '/materials/requests'
      fullPath: '/materials/requests'
      preLoaderRoute: typeof AppMaterialsRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materials/purchase-orders': {
      id: '/_app/materials/purchase-orders'
      path: '/materials/purchase-orders'
      fullPath: '/materials/purchase-orders'
      preLoaderRoute: typeof AppMaterialsPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materials/inventory': {
      id: '/_app/materials/inventory'
      path: '/materials/inventory'
      fullPath: '/materials/inventory'
      preLoaderRoute: typeof AppMaterialsInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materials/grn': {
      id: '/_app/materials/grn'
      path: '/materials/grn'
      fullPath: '/materials/grn'
      preLoaderRoute: typeof AppMaterialsGrnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labour/productivity': {
      id: '/_app/labour/productivity'
      path: '/labour/productivity'
      fullPath: '/labour/productivity'
      preLoaderRoute: typeof AppLabourProductivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labour/contractors': {
      id: '/_app/labour/contractors'
      path: '/labour/contractors'
      fullPath: '/labour/contractors'
      preLoaderRoute: typeof AppLabourContractorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labour/attendance': {
      id: '/_app/labour/attendance'
      path: '/labour/attendance'
      fullPath: '/labour/attendance'
      preLoaderRoute: typeof AppLabourAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/tracking': {
      id: '/_app/hr/tracking'
      path: '/hr/tracking'
      fullPath: '/hr/tracking'
      preLoaderRoute: typeof AppHrTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/settings': {
      id: '/_app/hr/settings'
      path: '/hr/settings'
      fullPath: '/hr/settings'
      preLoaderRoute: typeof AppHrSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/reports': {
      id: '/_app/hr/reports'
      path: '/hr/reports'
      fullPath: '/hr/reports'
      preLoaderRoute: typeof AppHrReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/payroll': {
      id: '/_app/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof AppHrPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/leave': {
      id: '/_app/hr/leave'
      path: '/hr/leave'
      fullPath: '/hr/leave'
      preLoaderRoute: typeof AppHrLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/attendance': {
      id: '/_app/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof AppHrAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDprRoute: typeof AppDprRoute
  AppMatrixRoute: typeof AppMatrixRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppHrAttendanceRoute: typeof AppHrAttendanceRoute
  AppHrLeaveRoute: typeof AppHrLeaveRoute
  AppHrPayrollRoute: typeof AppHrPayrollRoute
  AppHrReportsRoute: typeof AppHrReportsRoute
  AppHrSettingsRoute: typeof AppHrSettingsRoute
  AppHrTrackingRoute: typeof AppHrTrackingRoute
  AppLabourAttendanceRoute: typeof AppLabourAttendanceRoute
  AppLabourContractorsRoute: typeof AppLabourContractorsRoute
  AppLabourProductivityRoute: typeof AppLabourProductivityRoute
  AppMaterialsGrnRoute: typeof AppMaterialsGrnRoute
  AppMaterialsInventoryRoute: typeof AppMaterialsInventoryRoute
  AppMaterialsPurchaseOrdersRoute: typeof AppMaterialsPurchaseOrdersRoute
  AppMaterialsRequestsRoute: typeof AppMaterialsRequestsRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppTasksIdRoute: typeof AppTasksIdRoute
  AppHrIndexRoute: typeof AppHrIndexRoute
  AppLabourIndexRoute: typeof AppLabourIndexRoute
  AppMaterialsIndexRoute: typeof AppMaterialsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDprRoute: AppDprRoute,
  AppMatrixRoute: AppMatrixRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppHrAttendanceRoute: AppHrAttendanceRoute,
  AppHrLeaveRoute: AppHrLeaveRoute,
  AppHrPayrollRoute: AppHrPayrollRoute,
  AppHrReportsRoute: AppHrReportsRoute,
  AppHrSettingsRoute: AppHrSettingsRoute,
  AppHrTrackingRoute: AppHrTrackingRoute,
  AppLabourAttendanceRoute: AppLabourAttendanceRoute,
  AppLabourContractorsRoute: AppLabourContractorsRoute,
  AppLabourProductivityRoute: AppLabourProductivityRoute,
  AppMaterialsGrnRoute: AppMaterialsGrnRoute,
  AppMaterialsInventoryRoute: AppMaterialsInventoryRoute,
  AppMaterialsPurchaseOrdersRoute: AppMaterialsPurchaseOrdersRoute,
  AppMaterialsRequestsRoute: AppMaterialsRequestsRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppTasksIdRoute: AppTasksIdRoute,
  AppHrIndexRoute: AppHrIndexRoute,
  AppLabourIndexRoute: AppLabourIndexRoute,
  AppMaterialsIndexRoute: AppMaterialsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
